import React,{useEffect} from 'react';
import{motion}from'motion/react';
import{AlertTriangle,CheckCircle2,Clock3,DatabaseZap,FileSearch,GitBranch,ShieldAlert,ShieldCheck,WifiOff,X}from'lucide-react';
import{Check,SecurityStatus,Status}from'./types';
import{FreshnessBadge}from'./evidenceFeatures';
export const tone=(s:Status)=>s==='Compliant'||s==='Exempt'?'good':s==='Critical'?'bad':s==='Review'?'warn':s==='Unavailable'?'off':s==='Not Applicable'?'neutral':'info';
export function ArchivePanel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={'archive-panel '+className}>{children}</section>}
export function ArchiveDivider({label}:{label?:string}){return <div className="archive-divider" aria-hidden={!label}>{label&&<span>{label}</span>}</div>}
export function StatusPill({status}:{status:Status}){const Icon=status==='Compliant'||status==='Exempt'?CheckCircle2:status==='Critical'?ShieldAlert:status==='Unavailable'?WifiOff:status==='Review'?AlertTriangle:Clock3;return <span className={'pill '+tone(status)}><Icon size={13}/>{status}</span>}
export function SecurityPill({status}:{status:SecurityStatus}){const Icon=status==='SAFE'?ShieldCheck:status==='REVIEW'||status==='SUSPICIOUS'?ShieldAlert:Clock3;return <span className={'security-pill '+status.toLowerCase()}><Icon size={13}/>{status}</span>}
export function Metric({label,value,detail,toneName=''}:{label:string;value:string;detail:string;toneName?:string}){return <ArchivePanel className={'metric '+toneName}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></ArchivePanel>}
export function SourceMode({mode}:{mode:Check['mode']}){return <span className={'source '+mode.toLowerCase()}>{mode}</span>}
export function Progress({value}:{value:number}){return <div className="progress" aria-label={`${value}%`}><i style={{width:`${value}%`}}/></div>}
export function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><FileSearch/><b>{title}</b><span>{detail}</span></div>}
export function EvidenceDrawer({check,onClose,onAction,onOpenGraph}:{check:Check|null;onClose:()=>void;onAction:(action:string)=>void;onOpenGraph?:()=>void}){
 useEffect(()=>{if(!check)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;removeEventListener('keydown',key)}},[check,onClose]);
 if(!check)return null;
 return <motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.18}} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.aside initial={{x:32,opacity:0}} animate={{x:0,opacity:1}} transition={{type:'spring',stiffness:360,damping:38}} className="drawer" aria-label="Verification evidence" aria-modal="true" role="dialog">
  <header><div><span className="eyebrow">EVIDENCE RECORD · {check.ruleId}</span><h2>{check.label}</h2></div><button className="iconbtn" onClick={onClose} aria-label="Close"><X/></button></header>
  <div className="trace">{check.clause}<b>›</b> Applicability <b>›</b> Verification <b>›</b> <span>{check.status}</span></div>
  <div className="evidence-status"><StatusPill status={check.status}/><span>{check.confidence?`${check.confidence}% extraction confidence`:'Awaiting source'}</span><SourceMode mode={check.mode}/>{check.freshness&&<FreshnessBadge state={check.freshness.freshnessStatus}/>}</div>
  <section><h3>Why does this requirement apply?</h3><div className="applicability-box"><b>{check.applicability.state}</b><p>{check.applicability.reason}</p><span>Required evidence: {check.applicability.requiredEvidence}</span>{check.applicability.exemptionRuleId&&<code>{check.applicability.exemptionRuleId}</code>}</div></section>
  <section><h3>Rule and conclusion</h3><p>{check.note}</p><dl><div><dt>Tender clause</dt><dd>{check.clause}</dd></div><div><dt>Rule ID</dt><dd className="mono">{check.ruleId}</dd></div><div><dt>Evidence ID</dt><dd className="mono">{check.id}</dd></div><div><dt>Compliance result</dt><dd>{check.status}</dd></div></dl></section>
  {check.freshness&&<section><h3>Evidence freshness</h3><dl><div><dt>Verified at</dt><dd>{check.freshness.verifiedAt}</dd></div><div><dt>Fresh until</dt><dd>{check.freshness.freshUntil}</dd></div><div><dt>Age</dt><dd>{check.freshness.age}</dd></div><div><dt>Policy</dt><dd>{check.freshness.freshnessPolicy.label}</dd></div></dl></section>}
  <section><h3>Cross-source comparison</h3><div className="compare three"><div><span>Bidder submission</span><b>{check.submitted}</b></div><div><span>Document extraction</span><b>{check.extracted||'Not extracted'}</b></div><div><span>Provider / rule value</span><b>{check.verified}</b></div></div>{check.normalized&&<p className="normalized">Normalized legal entity: <b>{check.normalized}</b></p>}{check.discrepancies.map(d=><div className={'discrepancy '+d.severity} key={d.id}><b>{d.type}</b><span>{d.explanation}</span></div>)}</section>
  {check.details&&<section><h3>Verification details</h3><dl>{Object.entries(check.details).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>}
  <section><h3>Provenance</h3><div className="source-line"><DatabaseZap/><div><b>{check.source}</b><span><SourceMode mode={check.mode}/> · {check.mode==='UNAVAILABLE'?'No adverse inference':'Snapshot retained · SHA-256 sealed'}</span></div></div>{check.securityStatus&&<div className="security-line"><span>Document integrity</span><SecurityPill status={check.securityStatus}/></div>}<button className="filebtn" onClick={()=>onAction(`Opened ${check.evidence}`)}>{check.evidence}<span>Open →</span></button>{onOpenGraph&&<button className="open-graph" onClick={onOpenGraph}><GitBranch/> Open Evidence Graph</button>}</section>
  <section><h3>Officer action</h3><p className="muted">Only an authorized officer can change the review outcome. Every action is appended to the audit trail.</p><div className="actiongrid"><button onClick={()=>onAction('Finding accepted')}>Accept finding</button><button onClick={()=>onAction('Clarification requested')}>Request clarification</button><button onClick={()=>onAction('Finding flagged')}>Flag</button><button onClick={()=>onAction('Manual override started')}>Override…</button></div></section>
 </motion.aside></motion.div>
}
