import {ComplianceCoverage,DecisionSnapshot,DocumentIntegrityResult,EntityResolution,EvidenceEdge,EvidenceNode,EvidenceSnapshot,RelationshipSignal,RuleImpact,RuleTestCase} from './evidence.types';
const fresh={verifiedAt:'30 Sep 2026 · 14:31',freshnessPolicy:{id:'daily-final','label':'Reverify before final decision',maxAgeHours:168,reverifyBeforeDecision:true},freshUntil:'07 Oct 2026 · 14:31',age:'2 hours',freshnessStatus:'FRESH' as const};
export const evidenceNodes:EvidenceNode[]=[
 {id:'tender',category:'RULE',title:'CPCL/PROC/2026/041',subtitle:'Industrial Safety Valves',status:'ACTIVE',evidenceIds:[],details:{Type:'Tender'},criticalPath:true,x:40,y:90},
 {id:'clause',category:'RULE',title:'Tender Clause 4.2',subtitle:'Financial eligibility',status:'APPROVED',evidenceIds:['RULE-041-4.2'],details:{Page:'22','Original text':'Annual turnover shall be at least ₹50 Cr.'},criticalPath:true,x:250,y:90},
 {id:'rule',category:'RULE',title:'Turnover ≥ ₹50 Cr',subtitle:'Structured rule v2.1',status:'ACTIVE',evidenceIds:['RULE-041-4.2'],details:{Operator:'GTE',Threshold:'₹50 Cr'},criticalPath:true,x:460,y:90},
 {id:'claim',category:'FIELD',title:'Bidder claim ₹12 Cr',subtitle:'Submitted value',status:'REVIEW',evidenceIds:['EV-TURNOVER-12'],details:{Requirement:'₹50 Cr','Submitted value':'₹12 Cr'},criticalPath:true,x:670,y:20},
 {id:'document',category:'DOCUMENT',title:'Audited Statement',subtitle:'FIN-2025-26.pdf · page 17',status:'NORMAL',evidenceIds:['DOC-FIN-041'],details:{Page:'17',Hash:'8f2a…91c4',Integrity:'NORMAL'},criticalPath:true,x:670,y:160},
 {id:'field',category:'FIELD',title:'Extracted ₹12 Cr',subtitle:'96% extraction confidence',status:'VERIFIED EXTRACTION',evidenceIds:['FIELD-TURNOVER-17'],details:{Field:'Annual Turnover',Value:'₹12 Cr',Confidence:'96%'},criticalPath:true,x:880,y:160},
 {id:'source',category:'SOURCE',title:'Reference ₹50 Cr',subtitle:'MOCK trusted reference',status:'FRESH',evidenceIds:['SRC-FIN-041'],details:{Value:'₹50 Cr',Mode:'MOCK'},freshness:fresh,criticalPath:true,x:880,y:20},
 {id:'entity',category:'ENTITY',title:'Likely same entity',subtitle:'97% match confidence',status:'CONSISTENT',evidenceIds:['ENTITY-APEX-01'],details:{Canonical:'Apex Industrial Systems Private Limited',Signals:'PAN, address, normalized name'},criticalPath:false,x:670,y:300},
 {id:'finding',category:'FINDING',title:'TURNOVER MISMATCH',subtitle:'₹38 Cr below reference/threshold',status:'MANUAL REVIEW',evidenceIds:['FIND-TURNOVER-041'],details:{Difference:'₹38 Cr',Compliance:'NON_COMPLIANT',Confidence:'99%'},criticalPath:true,x:1090,y:90},
 {id:'risk',category:'RISK',title:'Medium risk contribution',subtitle:'+12 review priority',status:'REVIEW',evidenceIds:['RSK-26041-09'],details:{Reason:'Mandatory financial conflict'},criticalPath:true,x:1300,y:20},
 {id:'clarification',category:'CLARIFICATION',title:'Officer review',subtitle:'Clarification required',status:'OPEN',evidenceIds:['CLR-26041-04'],details:{Action:'Review conflicting evidence'},criticalPath:true,x:1300,y:160},
 {id:'decision',category:'DECISION',title:'Human decision pending',subtitle:'No automated disqualification',status:'PENDING',evidenceIds:[],details:{Owner:'Procurement Officer'},criticalPath:false,x:1510,y:90},
];
export const evidenceEdges:EvidenceEdge[]=[['tender','clause','contains'],['clause','rule','structures'],['rule','claim','applies to'],['claim','source','compared with'],['document','field','extracts'],['field','finding','contributes'],['source','finding','conflicts'],['entity','finding','resolves identity'],['finding','risk','prioritizes'],['finding','clarification','requires'],['risk','decision','informs'],['clarification','decision','precedes']].map((e,i)=>({id:`edge-${i}`,source:e[0],target:e[1],label:e[2],state:e[0]==='source'?'review':'verified'} as EvidenceEdge));
export const entityResolution:EntityResolution={canonicalName:'Apex Industrial Systems Private Limited',submittedNames:['Apex Industrial Systems Pvt Ltd','APEX INDUSTRIAL SYSTEMS PRIVATE LIMITED','APEX INDUSTRIAL SYSTEMS PVT LTD','Apex Industrial Systems Pvt. Ltd.'],confidence:97,result:'LIKELY SAME ENTITY',signals:[{label:'PAN match',state:'CONSISTENT',detail:'AAECA0000A across PAN, GST and Udyam'},{label:'Registered address',state:'CONSISTENT',detail:'Normalized address similarity 98%'},{label:'Legal-name normalization',state:'CONSISTENT',detail:'Pvt/Pvt./Private normalized consistently'},{label:'EPFO source',state:'UNAVAILABLE',detail:'No adverse inference while source is unavailable'}]};
export const relationshipSignals:RelationshipSignal[]=[{id:'REL-041-01',bidderA:'Apex Industrial Systems',bidderB:'Bharat Flow Controls',type:'Near-identical certification document',value:'98.9% visual/text similarity',confidence:98.9,severity:'Review',explanation:'Relationship signal; not evidence of collusion. The similarity may have legitimate explanations and requires human assessment.',evidenceIds:['DOC-CERT-APEX','DOC-CERT-BHARAT']}];
export const integrityResult:DocumentIntegrityResult={documentId:'DOC-FIN-041',mimeSignature:'PDF 1.7 · signature matches',fileSize:'2.8 MB',pageCount:24,sha256:'8f2a3c77d91e4b50…91c4',createdAt:'12 Sep 2026 · 09:14',modifiedAt:'12 Sep 2026 · 09:14',digitalSignature:'Valid synthetic signature',ocrTextConsistency:99.1,hiddenTextDifference:0.9,duplicatePages:0,unusualOverlays:0,extractionConfidence:96,nearDuplicateSimilarity:12,state:'NORMAL'};
export const evidenceSnapshots:EvidenceSnapshot[]=[['03 Sep','GST verified'],['12 Sep','OEM certificate uploaded'],['18 Sep','Tender opened'],['21 Sep','Clarification issued'],['23 Sep','Bidder responded'],['24 Sep','OEM reverified'],['26 Sep','Officer decision']].map((x,i)=>({id:`SNAP-${i+1}`,timestamp:x[0],label:x[1],nodeStates:{finding:i<3?'PENDING':i<5?'CLARIFICATION':'REVIEWED'},ruleVersion:i<2?'v2.0':'v2.1'}));
export const decisionSnapshots:DecisionSnapshot[]=evidenceSnapshots.map((s,i)=>({id:s.id,timestamp:s.timestamp,title:s.label,ruleVersion:s.ruleVersion,evidence:i<1?['GST snapshot']:['GST snapshot','OEM document'],findings:i<3?[]:['OEM validity finding'],actor:i%2?'A. Krishnan':'System'}));
export const ruleTests:RuleTestCase[]=[['₹80 Cr','PASS'],['₹50 Cr','PASS'],['₹49.99 Cr','FAIL'],['Missing','INSUFFICIENT EVIDENCE'],['Unreadable','MANUAL REVIEW'],['Startup exemption active','EXEMPT']].map((x,i)=>({id:`TEST-${i+1}`,input:x[0],expected:x[1],actual:x[1],passed:true}));
export const ruleImpact:RuleImpact={changedField:'Local-content threshold',from:'50%',to:'60%',affectedEvaluations:4,compliantResults:2,clarificationCases:3};
export const complianceCoverage:ComplianceCoverage[]=[['Statutory',8,8],['Identity',4,4],['Financial',3,4],['Local content',2,3],['OEM',1,2],['Tender specific',9,10]].map(x=>({category:String(x[0]),verified:Number(x[1]),total:Number(x[2])}));
